easyMenu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('intranet/', include('administracion.urls'), name='administracion'),
    path('', include('menu.urls'), name='menu'),
    path('pedidos/', include('pedidos.urls'), name='pedidos')
]

menu/urls.py
from django.urls import path
from .views import mostrar_productos, agregar_al_carrito, ver_carrito, eliminar_del_carrito

app_name='menu'

urlpatterns = [
    path('', mostrar_productos, name='menu'),
    path('agregar_al_carrito/', agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/', ver_carrito, name='ver_carrito'),
    path('eliminar_del_carrito/', eliminar_del_carrito, name='eliminar_del_carrito'),
]

pedidos/urls.py
from django.urls import path
from .views import ver_ordenes, ver_orden, actualizar_orden, borrar_orden

app_name = 'pedidos'	
			
urlpatterns = [
    # path('crear/', crear_orden, name='crear_orden'),
    path('', ver_ordenes, name='ver_ordenes'),
    path('ver/<int:numeroOrden>/', ver_orden, name='ver_orden'),
    path('actualizar/<int:numeroOrden>/', actualizar_orden, name='actualizar_orden'),
    path('borrar/<int:numeroOrden>/', borrar_orden, name='borrar_orden'),
]

pedidos/models.py
from django.db import models

# Create your models here.

pedidos/forms.py
from django import forms
from menu.models import Orden

class TotalInput(forms.TextInput):
    def get_context(self, name, value, attrs):
        return super().get_context(name, value, attrs)

class OrdenForm(forms.ModelForm):
    numeroOrden=forms.IntegerField(required=True, widget = forms.TextInput(attrs={'readonly':'readonly'}))
    total = forms.DecimalField(widget=TotalInput)

    class Meta:
        model = Orden
        fields = ['numeroOrden', 'mesa', 'mesero', 'codigoEstado', 'productos', 'total']

pedidos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OrdenForm
from menu.models import Orden
# from django.urls import reverse_lazy

def actualizar_orden(request, numeroOrden):
    orden = get_object_or_404(Orden, numeroOrden=numeroOrden)
    form = OrdenForm(request.POST or None, instance=orden)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('pedidos:ver_ordenes')
    return render(request, 'pedidos/actualizar_orden.html', {'orden': orden, 'form': form})

def ver_ordenes(request):
    ordenes = Orden.objects.all()
    return render(request, 'pedidos/ver_ordenes.html', {'ordenes': ordenes})

def ver_orden(request, numeroOrden):
    orden = get_object_or_404(Orden, numeroOrden=numeroOrden)
    return render(request, 'pedidos/ver_orden.html', {'orden': orden})

def borrar_orden(request, numeroOrden):
    orden = get_object_or_404(Orden, numeroOrden=numeroOrden)
    if request.method == 'POST':
        orden.delete()
        return redirect('pedidos:ver_ordenes')
    return render(request, 'pedidos/borrar_orden.html', {'orden': orden})

templates/pedidos/actualizar_orden.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}EasyMenu{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
    <br><br>
    <h1>Actualizar Orden {{orden.numeroOrden}}</h1>
    <form method="post">
      {% csrf_token %}
      <div style="display:none">{{ form.as_p }}</div>
      Estado: <br>{{ form.codigoEstado }}<br><br>
      <button type="submit" class="btn btn-success" value="Actualizar Estado">Actualizar Estado</button>
    </form>
  </div>
</body>
</html>

templates/pedidos/borrar_orden.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}EasyMenu{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container mt-5 ">
    <h5>Borrar Orden n° {{ orden.numeroOrden }}</h5>
    <p>¿Estás seguro de que deseas borrar la siguiente orden?</p>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="orden_id" value="{{ orden.pk }}">
        <button type="submit" class="btn btn-danger" value="Borrar Orden">Eliminar</button>
    </form>
</body>
</html>

templates/pedidos/ver_orden.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}EasyMenu{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
    <br><br>
    <h1>Detalles de la Orden</h1>
    <br>
    <div class="card" style="width: 18rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Número de Orden:</strong> {{ orden.numeroOrden }}</li>
        <li class="list-group-item"><strong>Fecha:</strong> {{ orden.fecha }}</li>
        <li class="list-group-item"><strong>Mesa:</strong> {{ orden.mesa }}</li>
        <li class="list-group-item"><strong>Mesero:</strong> {{ orden.mesero }}</li>
        <li class="list-group-item"><strong>Código de Estado:</strong> {{ orden.codigoEstado }}</li>
        <li class="list-group-item"><strong>Productos:</strong></li>
    {% comment %} <ul> {% endcomment %}
      {% comment %} {% for producto in orden.productos %}
        <li>{{ producto }}</li>
      {% endfor %}
    </ul> {% endcomment %}
        <li class="list-group-item"><strong>Total:</strong> {{ orden.total }}</li>
      </ul>
    </div>
</body>
</html>

templates/pedidos/ver_ordenes.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}EasyMenu{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
    <div class="container">
        <br><br>
        <h1>Órdenes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Número</th>
                    <th scope="col">Fecha / Hora</th>
                    <th scope="col">Mesa</th>      
                    <th scope="col">Estado</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for orden in ordenes %}
                <tr>
                    <td>{{ orden.numeroOrden }}</td>
                    <td>{{ orden.fecha }}</td>
                    <td>{{ orden.mesa }}</td>
                    <td>{{ orden.codigoEstado }}</td>
                    <td>
                        <a href="{% url 'pedidos:ver_orden' orden.numeroOrden %}">
                            <button class="btn btn-outline-primary">Ver</button>
                        </a>
                        <a href="{% url 'pedidos:actualizar_orden' orden.numeroOrden %}">
                            <button class="btn btn-outline-primary">Actualizar</button>
                        </a>
                        <a href="{% url 'pedidos:borrar_orden' orden.numeroOrden %}">
                            <button class="btn btn-outline-primary">Borrar</button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>